### ISSUE TITLE
Subcommand help

### ISSUE THREAD

**Issue by jsimnz** [codegangsta/cli#100]
I maybe missing this, and I have looked through most of the other issues both open and closed, but I cant find anything related to this issue/feature.

If I have a sub command of a command `cli command sub-command`, is there a help section for the `sub-command`.

When I run `cli help`, I get the global help template with commands and global flags, and when running `cli help command` I again get the help template with description and command specific flag options, but I can't seem to find anyway on getting help with sub-commands of a command.

IE
If I had a cli that had a command called `server`, and sub-commands to `server` called `start`, `stop`, etc... Is there a way to get a list of those sub-commands via help?

**Comment by jszwedko** [comment]
What @ghigt said. Closing this out, but feel free to re-open if you think `help <subcommand>` should also work.
