### ISSUE TITLE
Flags only accessible if global

### ISSUE THREAD

**Issue by jefferai** [codegangsta/cli#130]
Using cli current as of the time of filing this bug.

Following is a simplified version of my code:

```go
	app := cli.NewApp()
	app.Name = "orchid"
	app.Usage = "Orchid is a program"
	app.Version = Version
	app.Author = "Jeff"
	app.Email = "jeff@me.com"

	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "jsonfile, j",
			Value: "",
			Usage: "the JSON file to read for configuration information",
		},
	}

	app.Commands = []cli.Command{
		{
			Name:      "reconfigure",
			ShortName: "r",
			Usage:     "Perform reconfiguration",
			/*
				Flags: []cli.Flag{
					cli.StringFlag{
						Name:  "jsonfile, j",
						Value: "",
						Usage: "the JSON file to read for configuration information",
					},
				},
			*/
			Before: reconfigure.Validate,
			Action: func(c *cli.Context) {
				log.Printf("Context: %+v\n", c)
				log.Printf("Context App: %+v\n", c.App)
				log.Printf("Context flags: %+v\n", c.FlagNames())
				reconfigure.Run(c)
			},
		},
	}

	app.Run(os.Args)
```

Notice the commented out flag under the reconfigure subcommand. Currently, the program works as expected if, in reconfigure.Run, I reference c.GlobalString("jsonfile"). However, if I comment out the `jsonfile` flag from the global space and uncomment it in the reconfigure command, while the flag correctly shows in help text for the reconfigure command, I am unable to access it using c.String("jsonfile").

Am I misunderstanding something or is this a bug?

**Comment by jszwedko** [comment]
I believe some of this behaivour should have been fixed by #170, but yes, it would be useful to know how you are running the command. Please re-open if still an issue!
