### ISSUE TITLE
More control over usage string in subcommands

### ISSUE THREAD

**Issue by fawick** [codegangsta/cli#133]
I have a subcommand `mysub` that may have command options (flags) but must have exactly 2 arguments (non-flags). My command looks like this with the mandatory arguments `arg1` and `arg2`.
    
    tool mycmd mysub arg1 arg2

It's easy to setup my Action to check `len(c.Args()` to be 2. However, when I call 

    if len(c.Args()) != 2 { 
        fmt.Println("Error with arguments:", c.Args(), "\n")
        cli.ShowCommandHelp(c, "mysub")
        return
    }   

I get a usage string like 

    USAGE:
        command sub [command options] [arguments...]

That user string is implying that all arguments are optional. I'd rather present something like the following to indicate that I need exactly two parameters in a well-defined order.

    USAGE:
        command sub [command options] <arg1name> <arg2name>

I can achieve what I want with the following code, but it would be great if `cli` would offer direct means to that.

    if len(c.Args()) != 2 {
        fmt.Println("Error with arguments:", c.Args(), "\n")
        tmpl := cli.CommandHelpTemplate
        cli.CommandHelpTemplate = strings.Replace(cli.CommandHelpTemplate, "[arguments...]", "<arg1name> <arg2name>", -1)
        cli.ShowCommandHelp(c, "mysub")
        cli.CommandHelpTemplate = tmpl
        return
    }

(I'm aware that another means to my end would be to use flags for `arg1` and `arg2` and require that these flags are provided in my application logic.)

**Comment by jszwedko** [comment]
Going to roll this into #140 for discussion as the issues seem very closely related.
