### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by sqs** [codegangsta/cli#138]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with cli. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable cli on @Sourcegraph by going to https://sourcegraph.com/github.com/codegangsta/cli and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by jszwedko** [comment]
I think @codegangsta still needs to handle this as it appears to want an `owner` oauth token.

**Comment by apriendeau** [comment]
I can see this on sourcegraph now. Is this still an issue?

**Comment by jszwedko** [comment]
Indeed, this appears to be up there.
