### ISSUE TITLE
Support for dynamic (undefined) flags

### ISSUE THREAD

**Issue by DannyBen** [codegangsta/cli#144]
I was unable to figure this out from the documentation.
Is there any way right now to capture flags that were not defined in advance in cli.Command.Flags?
I would like to take all the supplied flags that were not handled, and do something with them.

I was hoping for something like this (c = Context)

	for flag := range c.ExtraFlags() {
		fmt.Println(flag.Name, flag.Value)
	}

**Comment by jszwedko** [comment]
Yeah, that would be tricky for the reasons @kytrinyx notes. I think something like that would be out-of-scope of this library, but could be useful as a standalone "arbitrary flag parser" that could be called with `app.Args()` that way it could be used standalone as well is with this library. Thank you for the suggestion though!
