### ISSUE TITLE
Creating a map of options

### ISSUE THREAD

**Issue by carlskii** [codegangsta/cli#162]
Hi,

I've been experimenting with your library but can't seem to work out how to build a map of the command line options that I can then reference from my own code. Is this possible? If so please could you provide an example.

Carl

**Comment by jszwedko** [comment]
@carlskii can you describe what you'd expect this map to contain and/or what you want to use it for? An example map definition would be helpful.

**Comment by jszwedko** [comment]
Closing, but please feel free to re-open with an example.
