### ISSUE TITLE
How best to propagate exit codes to main()?

### ISSUE THREAD

**Issue by cquinn** [codegangsta/cli#164]
We've found that using os.Exit(code) in our command functions makes them impossible to test reliably. But we do want to allow our command functions the ability to set the process exit code.

Our current hack is to just use a global variable, set it in the command function when non-zero, and call os.Exit() at the end of main(). But this doesn't seem very elegant.

It seems that there should be a way to pass the exit code back up to the app somehow. Maybe via the Context? We'd then still need a way to get it from main() since the Context is not available there, so maybe adding an App.After() function that could examine the context.ExitCode and decide what to do.

Thoughts?

**Comment by jszwedko** [comment]
Interesting question. You could do something like http://stackoverflow.com/a/26226382/2647163 describes with a mock "exiter" that you set to a no-op (or capture the exit code) during testing.

I personally do black box testing of the stuff in the `main` package via  https://github.com/sstephenson/bats, but you could do the same in Go using the `exec` package if desired.

**Comment by gdm85** [comment]
If it's about CLI..there should be support for exit codes :)
This, coupled together with #119, makes it really little useful to report failures...
