### ISSUE TITLE
How do i disable the built-in global options?

### ISSUE THREAD

**Issue by nomad-software** [codegangsta/cli#174]
How do i disable the built-in global flags? When i use the help command i get the following:
```
GLOBAL OPTIONS:
   --help, -h           show help
   --version, -v        print the version 
```
I don't want these in my application but i can't see a nice way to delete from the program. Any ideas?

**Comment by jszwedko** [comment]
There is a `HideVersion` and `HideHelp` field on `App`.

**Comment by nomad-software** [comment]
> There is a HideVersion and HideHelp field on App.

When these are set to true, the built-in `help` command is disabled and the `--version` global option is disabled. This still leaves the `--help` global option. I want to keep the `help` command but remove *all* global options.

It would be nicer if `app.HideHelp` removed the `--help` global option instead of the `help` command. As the `help` command can actually be overriden by using the `app.Commands` field.

**Comment by nomad-software** [comment]
Actually this is my bad. both `app.HideHelp` and `app.HideVersion` do indeed work as expected.
