### ISSUE TITLE
setting default value for a flag

### ISSUE THREAD

**Issue by nyumal** [codegangsta/cli#175]
the aim is to have the value of a flag (if it is set/used when the program is called) to be passed to the program as a varible if not use a default value. the code looks like this

```
Flags = []cli.Flags {
  Name: "myflag"
  Value: "default"
  Usage: "set custom value"
}

Action: func(c *cli.Context) {
  exec.Cmd("echo %s", myflag)
}
```

what is the best way to go about this?

**Comment by jszwedko** [comment]
@nyumal You can't define variables names dynamically in Go (even if you could it wouldn't be possible to do it in the scope of the function you pass as `Action`) . You'll need to use the accessor functions (`cli.String("myflag")` for example) to get the value as documented.

i.e. something like:

```go
Flags = []cli.Flags {cli.StringFlag{
  Name: "myflag"
  Value: "default"
  Usage: "set custom value"
},
}

Action: func(c *cli.Context) {
  fmt.Println(cli.String("myflag"))
}
```

**Comment by nyumal** [comment]
ahk that makes sense, thanks :+1:

**Comment by jszwedko** [comment]
:+1: no problem!
