### ISSUE TITLE
Command alias'?

### ISSUE THREAD

**Issue by ianneub** [codegangsta/cli#183]
Is it possible to have a single command with multiple names or multiple shortnames? For example:

```go
  app.Commands = []cli.Command{
    {
      Name:      "start, up",
      ShortName: "s, u",
      Usage:     "Start the docker engine",
      Action: func(c *cli.Context) {
        ...
      },
    },
  }
```

The use case is that some users can't seem to remember `start`, or would rather type `up` or vice versa.

**Comment by jszwedko** [comment]
Currently this is not directly supported, but you can emulate the behavior with something like:
```go
  upAction := func(c *cli.Context) {
  }
  app.Commands = []cli.Command{
    {
      Name:      "up",
      ShortName: "u",
      Usage:     "Start the docker engine",
      Action: upAction,
      {
      Name:      "start",
      ShortName: "s",
      Usage:     "Start the docker engine",
      Action: upAction,
    },
  }
```

**Comment by jszwedko** [comment]
I wouldn't mind just having a `Names` attribute that is a list of possible names rather than `Name` and `ShortName` though.

**Comment by ianneub** [comment]
> I wouldn't mind just having a Names attribute that is a list of possible names rather than Name and ShortName though.

:+1:

**Comment by jszwedko** [comment]
@ianneub added `Aliases` in #193.

**Comment by ianneub** [comment]
Right on. Thanks!
