### ISSUE TITLE
app.Commands docs are broken, Command.Names isn't a field

### ISSUE THREAD

**Issue by pwaller** [codegangsta/cli#203]
[This is the current master README](
https://github.com/codegangsta/cli/blame/2bcd11f863d540a1b190dc03b6c4f634c6ae91d4/README.md#L213), which has this example:

```go
app.Commands = []cli.Command{
  {
    Name:      "add",
    Names:     []string{"a"},
    Usage:     "add a task to the list",
    Action: func(c *cli.Context) {
      println("added task: ", c.Args().First())
    },
  }, ...}
```

However, on the very same branch, it appears that the struct doesn't have a [`Names`](https://github.com/codegangsta/cli/blob/2bcd11f863d540a1b190dc03b6c4f634c6ae91d4/command.go#L16).

/cc @jszwedko

**Comment by jszwedko** [comment]
Apologies for the confusion, I adjusted the `README` to reflect the API. Thanks!
