### ISSUE TITLE
Missing "Meta" field in StringFlag

### ISSUE THREAD

**Issue by abourget** [codegangsta/cli#212]
Right now, the `Value` is shown in the --help output. There are two purposes served by `Value`:

* show string flags that they take some 'string' value after the `--flag`
* serve as the default value for that flag

I propose adding a "Meta" field, and Meta would serve in this block: https://github.com/codegangsta/cli/blob/master/flag.go#L296-L302 whereas  `Value` would be used as the default value.  Maybe the template could show the default value as an addentum like `[default: VALUE]`.

**Comment by abourget** [comment]
Python's argparse calls it `meta`, whereas Go's kingpin calls it `PlaceHolder`.

**Comment by jszwedko** [comment]
Yeah, I am a fan of the `metavar` in `argparse`.

**Comment by jszwedko** [comment]
I think this is supported by https://github.com/codegangsta/cli/pull/357

**Comment by jszwedko** [comment]
Closing as #357 adds the meta behavior, but please feel free to reopen if you don't feel that that implementation supports the behavior you were looking for!
