### ISSUE TITLE
Distribution code completion.

### ISSUE THREAD

**Issue by Matt3o12** [codegangsta/cli#216]
As mentioned in this [stackoverflow comment](https://stackoverflow.com/questions/28823678/bash-autocomplete-using-codegangsta-cli-framework-https-github-com-codegangst#comment46156085_28824598), the docs currently lag support on how to distribute packages that use autocompletion.  

Could you please tell me how to distribute a `cli` package using autocompletion?

**Comment by jszwedko** [comment]
Added some instructions to the README in 942282e931e8286aa802a30b01fa7e16befb50f3, please let me know if they are unclear though. Thanks for raising the issue!

**Comment by Matt3o12** [comment]
Thanks.
