### ISSUE TITLE
Shell Application

### ISSUE THREAD

**Issue by manan19** [codegangsta/cli#220]
Feature Request - A functionality that allows developers to use the same commands in a shell like application.

```
$./cli
> foo
foo you
> bar
invalid params
> bar beer
here's your beer!

```

**Comment by jszwedko** [comment]
Hi @manan19, thank you for the suggestion. I think it's easy enough to compose CLI with `readline` (see @codegangsta doing it here https://github.com/codegangsta/hip/blob/master/hip.go#L64-L78) so I feel like we should leave this out of the core. This was also discussed as issue #44.

**Comment by jszwedko** [comment]
Let me know if you have any questions about composing this library with reading input lines though!

**Comment by manan19** [comment]
Thanks @jszwedko, that works fine for me.
