### ISSUE TITLE
Docs: BoolTFlag not documented

### ISSUE THREAD

**Issue by ahmetalpbalkan** [codegangsta/cli#223]
The difference between `cli.BoolTFlag` and `cli.BoolFlag` is not documented and therefore difficult to understand what is it without looking at the source code of the package or trying it out. 

The name `BoolTFlag` has meant nothing to me. My first guess is "a bool flag that's `true` by default"?

**Comment by jszwedko** [comment]
@ahmetalpbalkan yeah, the flags were sorely under documented, I've added docs for all of them at https://github.com/codegangsta/cli/pull/233 -- let me know if that addresses this!

**Comment by jszwedko** [comment]
Closing, but please re-open if you have any concerns with the additional docs.

**Comment by ahmetalpbalkan** [comment]
all good thanks @jszwedko
