### ISSUE TITLE
Why test files do have their own package (cli_test)

### ISSUE THREAD

**Issue by szank** [codegangsta/cli#236]
Hi, I have forked this repo to add some features that I needed. 
I was wondering why test files does have their own package. It is annoying, it took me some time to realize ( as this is not the usual way of doing things in go ). 
To write some new code I did have to either change all import clauses in test files to point to my package instead of github.com/codegangsta/cli or rename package cli_test to cli. Either way this is additional work every time i want to fork something, and then when i want to create pull request. 

I haven't seen such setup anywhere else. I would appreciate if you could please tell me why it is like this, and if I can raise a pull request to clean this up?

Best regards, 
Maciej

**Comment by polds** [comment]
@szank It's a good way to see how your package works when imported. When you have a test package that is "local" to your package then you have access to unexported variables and struct values that might not need to be exported (or shouldn't be). By putting your tests in a different package you can test the behavior your users will be experiencing.

**Comment by szank** [comment]
Hi @polds
This was a pain point when I first forked this project, I wasn't expecting to be forced to search and replace "import github.com/codegangsta/cli" into github.com/szank/cli before i run my code, and then do the reverse when I want to submit a pull request, then again to continue working on my fork

Unit tests are not meant to be a black box tests anyway, but I will respect your decision. 
I would like to suggest an improvement to this solution. 
Here https://golang.org/src/bufio/bufio_test.go for example package bufio is imported as 
```go
package bufio_test
import . "bufio"
```
This provides the solution you need without drawback I have just outlined. This is a needed improvement for anyone who forks this project imho.

**Comment by bryanl** [comment]
@szank, it isn't entirely obvious, but you don't have to change the imports. What you can do is add your fork as a remote to the git repo at ${GOPATH}/src/github.com/codegangsta/cli. This way, you can make your changes in your branch, but you still have the paths of the canonical repo.

**Comment by jszwedko** [comment]
Indeed, the typical workflow for forking a Go project is to fork it into the canonical path within your `$GOPATH` and add your fork as an upstream.

I.e.
```
git clone git@github.com:codegangsta/cli  ${GOPATH}/src/github.com/codegangsta/cli
cd ${GOPATH}/src/github.com/codegangsta/cli
git remote add fork git@github.com:szank/cli
```

**Comment by szank** [comment]
Hi,
I will use this approach then. Thanks for clearing it up ! 

Regards, 
Maciej
