### ISSUE TITLE
Distinguish between blank string flag and absence of flag

### ISSUE THREAD

**Issue by Gerg** [codegangsta/cli#239]
#### Feature Request
It would be useful if there was a way to distinguish between passing a string flag a blank string (`command -f ""`) and the absence of the flag (`command`).

Currently both will return `""` from `c.String("f")`

#### Our use case:
We have a command to update a resource via an API. Fields that can be updated are represented by different CLI flags. One of the fields on the resource is a string that can be blank. We would like users to be able to set the field to the blank string.

```bash
#Setting the field to non-blank string
command -f "string"

#Setting the field to blank string
command -f ""
```
To do this currently we have to have another flag to reset the field.
```bash
command --clear-field
```
This is annoying because it means we have two flags for a single field and have to handle cases where both flags are passed.

Thanks!

**Comment by jszwedko** [comment]
@Gerg you should be able to utilize `c.IsSet` and `c.GlobalIsSet` for this -- let me know if that helps.

**Comment by Gerg** [comment]
That is exactly what I'm looking for! Thanks :tada:

**Comment by feliksik** [comment]
c.IsSet() requires you to manually check this and generate an appropiate error message; would it make sense to delegate this to the parser as well, by setting a { Required = true } field in the generator struct of the Flag?

**Comment by jszwedko** [comment]
@feliksik there has been some talk about required flags, you can see #155 for the latest. Help wanted to take that over the finish line.
