### ISSUE TITLE
BoolTFlag returns false if no flag was set

### ISSUE THREAD

**Issue by szank** [codegangsta/cli#243]
Is is it a bug? I don't understand current usage of this flag. Currently if I check the value of this flag and it is false then user either wrote `app --booltflag="FALSE"` or `app` (without the flag). 

I would say that if flag defaults to true, it should return false if and only if  user writes `app --booltflag="FALSE"` in command line

**Comment by jszwedko** [comment]
Hi @szank your expectation of the behavior is correct and is what the library currently does. E.g.

```go
package main

import (
	"fmt"
	"os"

	"github.com/codegangsta/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name: "foo",
		},
	}
	app.Action = func(c *cli.Context) {
		fmt.Printf("%+v\n", c.BoolT("foo"))
	}

	app.Run(os.Args)
}
```

Prints `true` unless `--foo=false` is set.

**Comment by jszwedko** [comment]
Can you provide an example replicating the incorrect behavior you are seeing?

**Comment by szank** [comment]
Hi, 
Sorry for the wait, I was AFK for some time 

First, could you please explain me why are you using a StringFlag in your app.Flags array ? 
Shouldn't it be BoolT flag ?

Anyway, let's have a look at this piece of code : 
```go

// BoolTFlag this represents a boolean flag that is true by default, but can
// still be set to false by --some-flag=false
type BoolTFlag struct {
	Name   string
	Usage  string
	EnvVar string
}
```

and this one : 
```go 
// Looks up the value of a local boolT flag, returns false if no bool flag exists
func (c *Context) BoolT(name string) bool {
	return lookupBoolT(name, c.flagSet)
}
```

```go
func lookupBoolT(name string, set *flag.FlagSet) bool {
	f := set.Lookup(name)
	if f != nil {
		val, err := strconv.ParseBool(f.Value.String())
		if err != nil {
			return true
		}
		return val
	}

	return false
}
```

In the first comment it is said that the BoolT flag returns false if and only if in the command line 
you set  --some-flag=false,  while the latter piece of code shows that the BoolT call returns false when in the command line is  --some-flag=false arg OR there is no --some-flag set. 

I can prepare the code snippet that shows the issue, but this should be enough.

**Comment by jszwedko** [comment]
@szank I think you are confusing what `set.Lookup` does -- it only returns `nil` if the flag does not exist in the `FlagSet`. I.e. `BoolT` will return `false` if the flag is not defined at all, not that it is defined, but unspecified. See https://github.com/codegangsta/cli/blob/master/flag.go#L289-L307 for where the flag defaults to `true`.

Apologies for the copy/paste error in my example. Corrected example:

```
package main

import (
	"fmt"
	"os"

	"github.com/codegangsta/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.BoolTFlag{
			Name: "foo",
		},
	}
	app.Action = func(c *cli.Context) {
		fmt.Printf("%+v\n", c.BoolT("foo"))
	}

	app.Run(os.Args)
}
```

Also apologies for the delay!

**Comment by jszwedko** [comment]
Closing this out, but please reopen if you are still having issues!
