### ISSUE TITLE
Regression: global flags broken for app.Action

### ISSUE THREAD

**Issue by pwaller** [codegangsta/cli#252]
I've managed to bisect to 65d50017d4f34772b8d767fb7478b9416b5d30c5 (#227), which broke my usage of global flags, and caused quite a headache trying to determine what went wrong!

Consider the following program, which has one global flag, "foo". On 942282e, the commit before the regression, it correctly outputs `value=blah` when invoked as `./test --foo=blah`. After that commit, it just says `isset=false value=`.

```go
package main

import (
	"log"

	"github.com/codegangsta/cli"
)

func main() {
	a := cli.NewApp()

	a.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "foo",
			Value: "unset",
		},
	}

	a.Action = ActionMain

	a.RunAndExitOnError()
}

func ActionMain(c *cli.Context) {
	log.Printf("isset=%v value=%v", c.GlobalIsSet("foo"), c.GlobalString("foo"))
}
```

/cc @databus23

**Comment by databus23** [comment]
Outch! Good catch. I think I know what the problem is. I will look into this and try to fix it in a couple of hours.

**Comment by jszwedko** [comment]
@pwaller thanks for catching this! Apologies for the headaches.

**Comment by pwaller** [comment]
Thanks for the quick fix!
