### ISSUE TITLE
Version and Help Flag Parsing are not truly dynamic

### ISSUE THREAD

**Issue by apriendeau** [codegangsta/cli#254]
Given the situation below:
```go
cli.VersionFlag = cli.BoolFlag{
  Name: "version",
  Usage: "something",
}
var VerboseFlag = cli.BoolFlag{
	Name:  "verbose, v",
	Usage: "Enable verbose logging",
}

app := cli.NewApp()
app.Flags = []cli.Flag{VerboseFlag}
app.Run(os.Args)
```
`app --verbose` will still show execute showVersion

showVersion and showHelp do not conform to the new values.

Version:
https://github.com/codegangsta/cli/blob/f9982619ccace7df963bb7f6d1de3a6f014ff709/help.go#L187
Help:
https://github.com/codegangsta/cli/blob/f9982619ccace7df963bb7f6d1de3a6f014ff709/help.go#L196

**Comment by jszwedko** [comment]
@apriendeau definitely a bug, thanks for reporting!
