### ISSUE TITLE
Can't override defaults in slice flags?

### ISSUE THREAD

**Issue by wrouesnel** [codegangsta/cli#258]
Slice flags seem to have somewhat counter-intuitive behavior (or at least not specifiable).

I want to specify a default slice which is a known safe (or failsafe), but also want to allow the user to override it and specify a whole bunch of elements.

But if I do something like this:
```
cli.StringSliceFlag {
    		Name: "management-socket",
    		Value: &cli.StringSlice{"unix:///var/run/log_processor.socket",},
    		Usage: "Sockets (unix:// or tcp://) on which to serve the management interface",
    	},
```

Then what I get instead is that when I specify a command line option for that parameter - i.e.
`--management-socket tcp://0.0.0.0:8080` then that just gets appended to the default slice, rather then replacing it.

**Comment by jszwedko** [comment]
Yeah, this is definitely unexpected behavior.

**Comment by pjvds** [comment]
Duplicate of #160

**Comment by jszwedko** [comment]
Indeed, closing in lieu of #160 -- #350 should address it though.
