### ISSUE TITLE
printing help - manually

### ISSUE THREAD

**Issue by krzysztofantczak** [codegangsta/cli#268]
Hi,

Is it possible to somehow print help manually from inside of particular command/subcommand? My use case is with commands that should work only when proper set of flags was passed - otherwise help should be displayed. Not sure how can i achieve that atm.

Kind regards.

**Comment by jszwedko** [comment]
@krzysztofantczak you should be able to call `cli.ShowAppHelp`. It would be nice to have a `.Usage()` on the context struct though.

**Comment by jszwedko** [comment]
Let me know if that doesn't work for you!

**Comment by krzysztofantczak** [comment]
@jszwedko thanks for Your reply. It actually does work but, as i'm trying to use it with subcommand context i'd like to print help only for this subcommand (the same way it works with: app foo --help), but it seems that ```cli.ShowAppHelp(c)``` prints general usage for top app context. Usage/flags are defined for this subcommand, so i'm using it like this:

usage/flags part:
```
	c.Push(cli.Command{
		Name:      "tunnel",
		Aliases:     []string{"tun"},
		Usage:     "Manages tunnels",
		Action: 	execute,
		Flags: []cli.Flag {
			cli.BoolFlag{
				Name: "client, c",
				Usage: "tunnel client mode",
			},
			cli.BoolFlag{
				Name: "server, s",
				Usage: "tunnel server mode",
			},
			cli.StringFlag{
				Name: "connect",
				Usage: "server address for client mode",
			},
			cli.StringFlag{
				Name: "listen",
				Value: "0.0.0.0",
				Usage: "interface address for server mode",
			},
		},
	})
```

execution part:
```
func execute (c *cli.Context) {

	// server mode
	if c.Bool("server") == true {

		// do server stuff
	} else
	// client mode
	if c.Bool("client") == true {

		// do client stuff
	} else {
                // mode wasn't selected - print help for this subcommand
		cli.ShowAppHelp(c)
	}
}
```

**Comment by jszwedko** [comment]
@krzysztofantczak ah I see! In that case, I believe `ShowSubcommandHelp` should work for you.

**Comment by jszwedko** [comment]
Closing this, but please reopen if you feel that the issue wasn't addressed!
