### ISSUE TITLE
Exit code != 0 in case an invalid command is called?

### ISSUE THREAD

**Issue by viktorbenei** [codegangsta/cli#276]
It seems logical to expect a non zero exit code in case a non existing command is specified.

At the moment it just prints the info/warning message: `No help topic for 'asdf'`
But the exit code is 0

**Comment by caarlos0** [comment]
++

**Comment by viktorbenei** [comment]
Btw this issue is most significant in case another tool calls our cli tool, which expects a non zero exit code is an error happens. IMO a non defined command is clearly an error.

**Comment by mcvoid** [comment]
I disagree. Yes, invalid commands should return non-zero, but I don't think it's good default behavior for App.Run(). It's often the case with servers that many actions should be logged, and if a library I included invokes an os.Exit(1) on me before I can log it, I'd be furious. App.Run() already returns an error code that you can handle, and there exists a method App.RunAndExitOnError() which does the os.Exit(1) if you really do just want it to die right away.
