### ISSUE TITLE
Describe the the non-option arguments

### ISSUE THREAD

**Issue by laijs** [codegangsta/cli#277]
Some arguments have name, but the CLI help always show `[arguments...]` as in
`command subcommand [command options] [arguments...]`

Could we change it when user want specific the name for arguments? like
`brctl addif [command options] <brname> <ifname>`

**Comment by jszwedko** [comment]
This should be addressed by https://github.com/codegangsta/cli/pull/267

**Comment by jszwedko** [comment]
Closed by #267
