### ISSUE TITLE
recommended way to 'fail' a command

### ISSUE THREAD

**Issue by whyrusleeping** [codegangsta/cli#290]
What is the recommended way for a command to fail (and have a non-zero exit code). 

I'm currently just using `os.Exit(1)`, but i feel like the Action function could return an error to simplify that work.

**Comment by jszwedko** [comment]
@whyrusleeping agreed, having the command return an error would be ideal, but because it is an API breaking change, I'm reticent to make it until we cut a 2.0. See #266 for possible implementation.

**Comment by whyrusleeping** [comment]
@jszwedko ah, wonderful.

**Comment by jszwedko** [comment]
Supported by #361 thanks to @meatballhat !
