### ISSUE TITLE
USAGE output

### ISSUE THREAD

**Issue by abrahamrhoffman** [codegangsta/cli#300]
Hey there,

Love the package :+1: 

However, I was wondering if there was an easy way to modify the "USAGE" output. I would prefer to remove the '[global options] command [command options] [arguments...]' output.

Could you point me in the right direction?

Thanks,

Abe

**Comment by jszwedko** [comment]
Hi @abrahamrhoffman, you can override the output by setting the help template (https://github.com/codegangsta/cli/blob/master/help.go#L14) in your code. E.g.

```
...
cli.AppHelpTemplate = `NAME:
   {{.Name}} - {{.Usage}}
USAGE:
   {{.HelpName}} <your custom usage>
...
```

You can see the `App` struct for the values available (https://github.com/codegangsta/cli/blob/master/app.go#L13).

Let me know if this helps!

**Comment by abrahamrhoffman** [comment]
@jszwedko Thanks! That worked great! :dancers:
