### ISSUE TITLE
Add ability to get global and command level variables from a yaml file?

### ISSUE THREAD

**Issue by ChrisPRobinson** [codegangsta/cli#301]
I worked on a tool that leverages codegangsta cli library. As part of that work I wrapped much the cli to add the capability to get values from a yaml files. One for the global parameters one for the command parameters.

By default there would be a global file called .test.config.yml that global parameters could be pulled from. The name of the file could be configurable.

The precedence would be if a value was specified on the command line it had the highest precedence, followed by and env variable, followed by a value in the yaml file.

Below is a pseudo design as I'm just trying to get across the idea.

For a command, add fields: 
cli.Command   
   AllowFileInput string // allows the command to accept input from a file
   FileInputFlagName string  // defaults to "load"

For Flag we can add to the the following fields
   AllowFileInput // indicates that this flag value can be found in the file. 

The files I pulled from were from a yaml file

We also have a version flag built into the file as well and when the file is loaded if the file doesn't meet a particular version it will error.

There are a couple of problems where I can see this getting a little complicated like pulling generic values, it could be a tricky to map, I didn't support this as we didn't need anything like that. I suppose on a first stab we can exclude pull parameters like that.

Would this be an interesting capability for me to create a pull request along those lines? It would take a little time as I'd need to rework what I have to the internal code and rework the tests of course. Just trying to give to something I've used.

**Comment by jszwedko** [comment]
Hi @ChrisPRobinson, thanks for bringing this up! There was a little discussion around this in #235.

I think this functionality would be very useful and would be open to a pull request introducing it. I think it would be nice to see it architected as add-on functionality if at all possible rather than changing the existing interface. A half-baked idea may be to introduce a subpackage that defines another set of flags that wraps the existing flags (and still satisfies the interface) but sets the default value based on a passed in configuration file. So that you could then do something like:

```go
config := cflag.NewProvider("somefile.yaml")
myCommand.Flags = []cli.Flag{cflag.IntFlag{Name: "foo", Value: 123, ConfigProvider: config}}
```

I think this would approach would be more flexible (support could be added for INI, JSON, etc.).

**Comment by ChrisPRobinson** [comment]
Cool, I'm glad people are interested in this functionality.

The approach you outlined is interesting, I hadn't exactly thought of that. I was attempting to make a pull request and I came up with something slightly different. Its totally not ready but here is what I had.

```
I made a new interface called FlagApplyExtension. 
type FlagApplyExtension interface {
	ApplyContext(*FlagSetContext)
}

type FlagSetContext struct {
	set             *flag.FlagSet
	inputSourceData InputSourceFlagProviderData
}
```
I also made two other interfaces as well

```
type InputSourceFlagProvider interface {
	LoadFlag() Flag
	Data(c *Context) (InputSourceFlagProviderData, error)
}

type InputSourceFlagProviderData interface {
	IsFlagSpecified(name string) bool
	Int(name string) int
	Duration(name string) time.Duration
	Float64(name string) float64
	Bool(name string) bool
	BoolT(name string) bool
	String(name string) string
	StringSlice(name string) []string
	IntSlice(name string) []int
	Generic(name string) interface{}
}
```
The idea was to have a different implementation for the sourceProvider. It can be ini, yaml, whatever. I made a providerData implementation that can handle a map. Then i wrote a yaml data source impl that would read the data in and be able to use map data impl. I tweaked the command execution ever so slightly to invoke the new interface if it existed otherwise to you use the other one. In the core it would only look at the InputSource if it wasn't nil, otherwise all the code stayed the same.

I set the sourceProvider on the Command itself. From there it would flow down to the flags. You would only indicate if you wanted the flag to be read or not. Also I would inject an input flag as well that could be used.

I was just trying things out this way. If I were to follow what you are describing I would also want to not have to specify for each flag the config provider, rather have that at the command level. I would need to implement something for that too. 

Perhaps this is too much detail, probably the best thing is to just nail down the api that we want people to use and work from there.

**Comment by ChrisPRobinson** [comment]
Oh and I forgot to mention, I wanted the config file path to be parameterizable. In your example above you have to specify the file directly. I wanted one flag to be specified on the command itself. That would be the connection parameter. In my sample I would create a default "load" flag. This parameter is used to load. This also changes up how to initialize everything. You can get a cli.Context to get the flag value until they are all already parsed.

**Comment by ChrisPRobinson** [comment]
One last note, the design I made doesn't fully work yet because of the fact that you want to be able to get some of the values that were already parsed to figure out where the yaml/configuration file is. There has to be a first pass that parses all the values. Then afterwards the config file is parsed and values are overridden if they are empty or default values.

**Comment by zpatrick** [comment]
+1

**Comment by solher** [comment]
+1

**Comment by zpatrick** [comment]
One issue that you've touched on is the precedence of different configuration sources (command line vs yaml file, etc). This gets pretty difficult to manage the more sources you add (e.g think of adding environment variables to your new flag objects).

I'm working on a project that addresses that issue (it sounds very similar to your original project. Shameless plug: https://github.com/zpatrick/go-config), and I think a very flexible and useful feature side projects like ours could use is to be able to set flag values after parsing the in "context" object. 

There's an old feature request at: https://github.com/codegangsta/cli/pull/234 which tries to accomplish that. I don't see much movement on I though. I think adding that feature in this mr will make it much more valuable. It opens the door for arbitrary flag providers, not just the ini, yaml, etc that get built in this repository.

**Comment by ChrisPRobinson** [comment]
@zpatrick Thanks for the link, I'll take a look at it. 
I'm working on a prototype that "gets things working" not that I want that pushed in, just as a starting point.

One of the difficulties I'm having is getting the precedence working correctly, at least in the order I'm interested in. first specified args, then env vars, then yaml, then defaults. 
In the work I've done I think I have an idea on how I can make which value that is chosen a more composable operation. 
Might be able to get something out this weekend. But it won't be the real thing, just an initial cut to make for more discussion. I'd like to alter some of the internals if I can, I think this might open customizations a bit more.

**Comment by ChrisPRobinson** [comment]
https://github.com/ChrisPRobinson/cli/pull/1 - Need to do more work to make something workable along the lines that @jszwedko was talking about, though putting this out there to view. The next work I do I'm going to take the cli.Context refactor I made and then make new flags in another package along the lines that was discussed above. I'm going to aim to make something a bit composable for how it gets the values.

**Comment by ChrisPRobinson** [comment]
Another Prototype impl, tried to reduce the set of changes to core files- https://github.com/ChrisPRobinson/cli/pull/2/files

**Comment by ChrisPRobinson** [comment]
Ok after a bunch of experimentation I've gone more of the way that @jszwedko suggested in the first place. I forgot about the power of embedding a struct in an existing one. It will also allow others to be able to create other input sources other than yaml. Defining the flags seems ok.

https://github.com/ChrisPRobinson/cli/pull/3

Probably easiest way to see how people would use it is to look at the tests
https://github.com/ChrisPRobinson/cli/pull/3/files#diff-bbc8ba4cb51df0fc39d93d43e810f54f

I welcome any comments. 

I'll just start working on implementing the rest of the functionality and adding tests as well.

**Comment by ChrisPRobinson** [comment]
pull request opened that can add this functionality. Still need to do work to get this to build correctly.
https://github.com/codegangsta/cli/pull/306

**Comment by jszwedko** [comment]
Never actually closed this issue out. Thank you so much for the implementation @ChrisPRobinson !
