### ISSUE TITLE
Is it possible to change the usage format in the help command?

### ISSUE THREAD

**Issue by TylerPachal** [codegangsta/cli#302]
My app requires a command line argument (a date) to be provided, and I am wondering how I can update the `--help` command to reflect this.

---

The current output of the `--help` command is as follows:

    NAME:
       application - Usage usage usage
    
    USAGE:
       application [global options] command [command options] [arguments...]

    ...etc

---

I want to achieve something like this, where I could indicate to the user that there is a required argument:

    NAME:
       application - Usage usage usage
    
    USAGE:
       application <required date> [global options] command [command options]  [arguments...]
    
    ...etc

**Comment by jszwedko** [comment]
@TylerPachal you can use `.ArgsUsage` on `Command` to specify required arguments.

Let me know if this helps!

**Comment by TylerPachal** [comment]
Perfect.  Thanks!
