### ISSUE TITLE
Version and author(s) fields should be at the end of help text

### ISSUE THREAD

**Issue by osocurioso** [codegangsta/cli#303]
When reading help text I'm usually more interested in how to use the command than in author/version/license information.

It would be great if author and version info was grouped together with license at the end.

**Comment by jszwedko** [comment]
Agreed :+1:

**Comment by frankcarey** [comment]
Though I agree, you can simply override this in your own app.. We've also updated it to also hide commands that have "cmd.HideHelp: true" set, but it should give you the right idea.

```Go
 cli.AppHelpTemplate = `NAME:
248    {{.Name}} - {{.Usage}}
249 USAGE:
250    {{.HelpName}} {{if .Flags}}[global options]{{end}}{{if .Commands}} command [command options]{{end}} {{if .ArgsUsage}}{{.ArgsUsage}}{{else}}[arguments...]{{end}}
251    {{if len .Authors}}
252 AUTHOR(S):
253    {{range .Authors}}{{ . }}{{end}}
254    {{end}}{{if .Commands}}
255 COMMANDS:
256 {{range .Commands}}{{if not .HideHelp}}   {{join .Names ", "}}{{ "\t" }}{{.Usage}}{{ "\n" }}{{end}}{{end}}{{end}}{{if .Flags}}
257 GLOBAL OPTIONS:
258    {{range .Flags}}{{.}}
259    {{end}}{{end}}{{if .Copyright }}
260 COPYRIGHT:
261    {{.Copyright}}
262    {{end}}{{if .Version}}
263 VERSION:
264    {{.Version}}
265    {{end}}
266 `
```

**Comment by meatballhat** [comment]
@frankcarey Thanks for the great example!  I'm adding it to the docs :smiley_cat: (https://github.com/codegangsta/cli/pull/373)
