### ISSUE TITLE
EnvVar shadows command line parameters

### ISSUE THREAD

**Issue by icexin** [codegangsta/cli#307]
When EnvVar value is set on global flags, command line parameters has no effective.

**Comment by paddie** [comment]
bump, I'm fighting this right now.

**Comment by icexin** [comment]
I fault, this happens only on `StringSlice` as described on #160, other flag works well.

**Comment by jszwedko** [comment]
Fixed by #392 (will be released is v2, but you can use that branch for now if you need the functionality sooner!).
