### ISSUE TITLE
app.Before is swallowing the returned error

### ISSUE THREAD

**Issue by ahmetalpbalkan** [codegangsta/cli#310]
```
    // An action to execute before any subcommands are run, but after the context is ready
    // If a non-nil error is returned, no subcommands are run
    Before func(context *Context) error
```

Inside the `Before` function, if I return an error, it just exits the program silently (as advertised does not execute the subcommands) but it does not print the returned error to the output.

I can hardly imagine this behavior being useful to anyone.

If we want to stop processing based on the return value, we could've been returning a `bool` instead of an `error`, right?

If I am returning an `error`, then I'd assume that `cli` package is going to print that to the screen nicely before exiting.

**Comment by jszwedko** [comment]
@ahmetalpbalkan the error should bubble back up and be returned by `app.Run` -- are you not seeing that?

**Comment by jszwedko** [comment]
You can also take advantage of `App.RunAndExitOnError`

**Comment by ahmetalpbalkan** [comment]
@jszwedko I never paid attention to the fact that `app.Run()`'s [signature](https://godoc.org/github.com/codegangsta/cli#App.Run), I just found out with your response that it returns `error`. The examples in the [README.md](https://github.com/codegangsta/cli/blob/c31a7975863e7810c92e2e288a9ab074f9a88f29/README.md) are very misleading. They're not handling the error and the app would exit silently on an error. I think that's not very good.

But that solves my problem, so closing this one. Thanks.
