### ISSUE TITLE
Querying flags without a destination doesn't work.

### ISSUE THREAD

**Issue by NlightNFotis** [codegangsta/cli#316]
Hello,

I am using this package to implement a CLI application. I replicated the code from the documentation in the readme file to implement some basic flags, having essentially something like this:

```go
...
app.Flags = []cli.Flag {
  cli.StringFlag{
    Name: "date, d",
    Usage: "Optional parameter for some of the api calls",
  },
}
app.Action = func(c *cli.Context) {
  fmt.Printf("%v\n", c.String("date")
}

```

and frankly, this doesn't work - where work means that it prints nothing, essentially `""`. For it to work, it required creating a new `var date string` and placing it as a `Destination: &date` for me to be able to query the flag contents, when the documentation suggests otherwise. 

I can also replicate this behavior in both Windows 8 `cmd.exe` and under `bash` in Debian 8.

**Comment by NlightNFotis** [comment]
I also managed to replicate this behavior with an `IntFlag`. This too, requires an earlier defined int variable set as a `Destination` for it to work.

**Comment by jszwedko** [comment]
Hi @NlightNFotis!

I was unable to replicate this with the following:
```
➜  ~  cat /tmp/tmp.go
package main

import (
	"fmt"
	"os"

	"github.com/codegangsta/cli"
)

func main() {
	app := cli.NewApp()
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "date, d",
			Usage: "Optional parameter for some of the api calls",
		},
	}
	app.Action = func(c *cli.Context) {
		fmt.Printf("%v\n", c.String("date"))
	}

	app.Run(os.Args)
}
➜  ~  go run /tmp/tmp.go -d some-date
some-date
```

Can you post a full example?

**Comment by NlightNFotis** [comment]
Hello @jszwedko !

First of all, thank you for your quick response! 

Given the code you gave me, I too was unable to reproduce the problem. I isolated the part of my code that is causing me the issues however, and it seems that the issue persists.

My code is the following:
```go

package main

import (
    "fmt"
    "os"

    "github.com/codegangsta/cli"
)

func main() {
    app := cli.NewApp()
    app.Flags = []cli.Flag{
        cli.StringFlag{
            Name:  "date, d",
            Usage: "Optional parameter for some of the api calls",
        },
    }
    app.Commands = []cli.Command{
      {
        Name:  "backups",
        Usage: "Show a list of backups of your application or user",
        Action: func(c *cli.Context) {
          fmt.Printf("%v\n", c.String("date"))

          if len(c.Args()) == 0 {
              //backup(c, configuration, "list_user")
          } else if len(c.Args()) == 1 {
              // backup(c, configuration, "list_domain")
          } else if len(c.Args()) == 2 {
              // backup(c, configuration, "list_domain_timed")
          }
        },
      },
    }

    app.Run(os.Args)
}
```

I only have one relevant positional argument and one relevant optional argument (the flag). It seems that what's different between my code and yours is the `app.Action` in your code being replaced by a list of `app.Commands` in mine. Maybe the integration between the two different parts is causing these issues?

**Comment by NlightNFotis** [comment]
To be more precise, running the code I supplied you with, results in the following CLI interaction:

```sh

C:\Users\f.koutoulakis\Documents\GitHub\cli (master)
λ .\experimentz.exe --date=20101010 backups

C:\Users\f.koutoulakis\Documents\GitHub\cli (master)
```

when the expected interaction is:


```sh

C:\Users\f.koutoulakis\Documents\GitHub\cli (master)
λ .\experimentz.exe --date=20101010 backups
20101010
C:\Users\f.koutoulakis\Documents\GitHub\cli (master)
```

**Comment by NlightNFotis** [comment]
Making a tiny bit change in the code that I pasted earlier, adding a destination and an associated variable, seems to result in the expected interaction for me:

(Correct code, that demonstrates the behavior as expected)
```go

package main

import (
    "fmt"
    "os"

    "github.com/codegangsta/cli"
)

var date string

func main() {
    app := cli.NewApp()
    app.Flags = []cli.Flag{
        cli.StringFlag{
            Name:  "date, d",
            Usage: "Optional parameter for some of the api calls",
        },
    }
    app.Commands = []cli.Command{
      {
        Name:  "backups",
        Destination: &date,
        Usage: "Show a list of backups of your application or user",
        Action: func(c *cli.Context) {
          fmt.Printf("%v\n", date)

          if len(c.Args()) == 0 {
              //backup(c, configuration, "list_user")
          } else if len(c.Args()) == 1 {
              // backup(c, configuration, "list_domain")
          } else if len(c.Args()) == 2 {
              // backup(c, configuration, "list_domain_timed")
          }
        },
      },
    }

    app.Run(os.Args)
}

**Comment by jszwedko** [comment]
Hi @NlightNFotis! Apologies for the delay.

So, in this case, you actually want to use `GlobalString()` to access the top level flag from within the subcommand. I concede that this behaviour is a bit awkward, but difficult to change while maintaining backwards compatibility. If we get to do a version 2 it is high on the list of things I want to change (i.e. have `String()` recurse up the contexts until it finds the flag).

**Comment by jszwedko** [comment]
Closing, but let me know if you have any additional questions.
