### ISSUE TITLE
Mishandling of a single dash "-" as argument causes re-ordering of non-flag arguments

### ISSUE THREAD

**Issue by andreas-kupries** [codegangsta/cli#324]
Many a cli which takes a path-argument somewhere will also accept the single dash ("-") as argument, with the meaning of "use stdin".

If the argument accepting the dash is not the first argument, and the command is not given any other options before then the package will mis-identify the dash as a flag-option and re-order the command line for parsing by go flags. go flags then considers the dash as a non-flag argument and leaves it in-place. In the end the command router sees a re-ordered command line.

Examples

|command line|slice seen by router|notes|
|----|----|----|
|foo read -something key -|[key -]|Use of -something pre-empted the issue|
|foo read key -|[- key]|The dash is re-ordered to come before the key|

The issue is at [https://github.com/codegangsta/cli/blob/f3c8e07836a9d73d1183d8990c2017a589cd1eb3/command.go#L84], where the loop for finding both terminator and first flag checks only that arguments begin with a dash. As the dash-character alone is not a proper flag it should not be considered as a possible fist flag argument.

The PR [https://github.com/codegangsta/cli/pull/323] contains a new test demonstrating the issue, and a possible fix for it.

**Comment by jszwedko** [comment]
Very descriptive issue report, thank you!

**Comment by jszwedko** [comment]
Addressed by your PR #323 -- thanks again!
