### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by hafe** [codegangsta/cli#325]
How do I 1) define new global options and 2) use them in a subsequent command?
An example would be global option "--debug" 
Thanks, Hans

**Comment by jszwedko** [comment]
Hi @hafe, you can define flags on the app itself `app.Flag` and retrieve them via the methods on `Context` that are prefixed with `Global`, e.g. `GlobalInt` (see https://godoc.org/github.com/codegangsta/cli#Context).

Please let me know if this helps!

**Comment by jszwedko** [comment]
See https://github.com/codegangsta/cli/blob/master/app_test.go#L630-L645 for another example.

**Comment by jszwedko** [comment]
Closing, but let me know if you have questions.

**Comment by hafe** [comment]
I got it to work as you said. A global flag (--debug/-d) checked by a "before action" that in turn sets up the debug log level
Thanks a lot!
Hans

**Comment by gobins** [comment]
@hafe did you get this working. I'm stuck at trying to pass the debug flag. When running a sub command and passing the debug global flag, I'm always getting an error "Incorrect Usage".

**Comment by jszwedko** [comment]
@gobins note that global flags need to appear before subcommands, i.e.:

```
my-command --foo=1 bar

vs.

my-command bar --foo=1
```

**Comment by hafe** [comment]
@gobins yes I got it work, as I said simply using a before action, something like:

func beforeAction(c *cli.Context) error {
	if c.GlobalIsSet("debug") {
		SetDebug()
	}
	return nil
}

Guess you could do something similar in the command itself provided you have passed the context to it

**Comment by gobins** [comment]
@jszwedko thanks for clearing that up. It is working now when I place it before the subcommand.

Thanks @hafe for the example.

**Comment by tuannvm** [comment]
I use this approach:

```go
func main() {
	flags := []cli.Flag{
		cli.StringFlag{
			Name:   "flag1",
			Usage:  "Flag 1",
		},
		cli.StringFlag{
			Name:   "flag2",
			Usage:  "flag 2",
		},
	}

	app.Commands = []cli.Command{
		{
			Name:    "sub command",
			Flags:   flags,
			Action: func(c *cli.Context) error {
				return nil
			},
		},
	}

  app.Flags = flags
```
