### ISSUE TITLE
Named / fixed arguments 

### ISSUE THREAD

**Issue by draxil** [codegangsta/cli#327]
There seems to be no way (apologies if I am missing it) to define fixed / named arguments for the app or subcommands. So following the git example if I were implementing "checkout" like subcommand, I'd want help that says:

> mygit checkout  [<branch>]

And the option to vet unwarranted extra Args  for situations like:

> mygit checkout x y 

Where I'd want to blow up and show the usage. I'm tempted to try and implement this myself, but I'm not sure I've thought it through fully. I am guessing on the define side, a syntax like:

>cli.Command{
>     Name: "checkout",
>    PositionalArgs: []cli.StringArg{
>            Name: "branch",
>           Optional: true,
>            Value: &x
>    }
>}

You'd need the "Optional" part so you'd know whether to wrap the square brackets around the arg in usage. Any thoughts?

**Comment by draxil** [comment]
Ah, I've now found "ArgsUsage" which solves a lot of the problem. Would still be nice to make it possible to handle this though?

**Comment by jszwedko** [comment]
Agreed! There has been some discussion about this in #240 and the start of implementation in #140 which might interest you.

**Comment by jszwedko** [comment]
Closing this as a duplicate, but please feel free to comment on / follow these!
