### ISSUE TITLE
Release branches

### ISSUE THREAD

**Issue by blaubaer** [codegangsta/cli#330]
What do you think about release branches? That results in stable and reliable versions of ``codegangsta/cli``. The ``master`` is still the newest version of it - but sometimes they are branches created like ``v1``, ``v2``, ...
```go
// Usage:
import "gopkg.in/codegangsta/cli.v1"
// or ...
import "gopkg.in/codegangsta/cli.v2"
// ...
```

See http://labix.org/gopkg.in for more information.

**Comment by jszwedko** [comment]
:+1: I think that is a good idea when/if we start work on a v2 of this library. Currently there are tags that you can use with `gopkg.in`, e.g. `gopkg.in/codegangsta/cli.v1.2.0`. Admittedly I have not been keeping up with releases.

**Comment by blaubaer** [comment]
Ok. Good to know. :relaxed:

**Comment by meatballhat** [comment]
Tags have been filled in for v1.2.0-present.  Please yell if the tag you're looking for isn't available 😸
