### ISSUE TITLE
Insufficient option usage help

### ISSUE THREAD

**Issue by atombender** [codegangsta/cli#333]
It's possible to write this:

```go
		cli.StringFlag{
			Name:  "config, c",
			Usage: "Load configuration from this file",
		},
```

Now the help says:

```
GLOBAL OPTIONS:
   --config, -c 	Load configuration from this file
  [...]
```

But this doesn't tell the end user that the flag takes a value. The usual way is to show that it is:

```
   --config FILE, -c FILE	Load configuration from FILE
```

As far as I can see, you can't do this. The `flag` package, of course, has its own way:

```go
flag.String("c", "", "Load configuration from `file`")
```

Here, the backtick-enclosed part of the help will be used to infer what the name of the value is.

**Comment by jszwedko** [comment]
Agreed, support for placeholders would be nice. Thanks for the idea!
