### ISSUE TITLE
App.Before looks like it executes before sub commands but comments say it executes after

### ISSUE THREAD

**Issue by gaffo** [codegangsta/cli#337]
Which is correct. If after I'd like a good way to set global options on my app before my subcommands execute like for instance:

command -v subcommand --flag value

so that I can take -v and turn on verbose logging for all of the subcommands without reepeating the code. Or is there a way to do this already?

**Comment by jszwedko** [comment]
Hi @gaffo 

`App.Before` will run before any subcommands which is also what the comments state (https://github.com/codegangsta/cli/blob/master/app.go#L41-L44). Were there other comments you were looking at?

**Comment by hafe** [comment]
Also see https://github.com/codegangsta/cli/issues/325
