### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by onlyjob** [codegangsta/cli#347]
Last release was a while ago so some packages started to bundle unreleased snapshots...
New release would be much appreciated. Thanks.

**Comment by nathan-osman** [comment]
Indeed, this is preventing me from importing `cli` from http://gopkg.in, since I need `ArgsUsage`.

**Comment by meatballhat** [comment]
Done!  #360 clarifies what's where, but the tags are available now.

**Comment by onlyjob** [comment]
Thanks!! :)
