### ISSUE TITLE
Seems no way to tell whether a value is from cli input or default

### ISSUE THREAD

**Issue by elgs** [codegangsta/cli#356]
In my app, the precedence of the value being used is like this: cli input > config file value > cli default value. Now if I get the value which happens to be the default cli value, I need to differentiate whether it's from cli input explicitly by the user, or it is from the cli default implicitly. This matters because it decides whether to use the happen-to-be default value or the value in the config file. So is there a way differentiate them? Thanks.

**Comment by elgs** [comment]
Essentially, when a user input option happens to be the same as the default value, there's no way to tell whether the value if from user input or the default value. They have different priorities.

**Comment by jszwedko** [comment]
Hi @elgs,

I'd need to look to double check how this plays with the new `altsrc` package, but you should be able to use `context.IsSet` to check if the user specified the flag.

**Comment by elgs** [comment]
Thanks @jszwedko! `context.IsSet` does the trick.
