### ISSUE TITLE
why do not build executable binary file in current path?

### ISSUE THREAD

**Issue by xuxiangyang** [codegangsta/cli#359]
Hi， I have a question, why when I run `go run cli.go`, `os.Getwd()` return a path like this `/private/var/folders/bt/wq6vgz511576mz4l7_4m075c0000gn/T/go-build141992156/command-line-arguments/_obj/exe`

my program should read some config files under relative path, if cli do not build a binary under current path, it could not read the files. How could I avoid this?

I need some help, Thx

**Comment by xuxiangyang** [comment]
if I do not use the cli, just run `go run main.go`, every thing work fine. How could I solve this?

**Comment by jszwedko** [comment]
Hi @xuxiangyang,

`go run` automatically builds and executes the binary for you in a temporary location. More typically you would do `go build .` and then `./<your-program>`. Try this and see if it works.

I actually wasn't able to reproduce this on Go 1.5.3 on Linux, but from your temporary file path it seems that you are on OSX.

```➜  ~ cat tmp.go 
package main

import (
	"fmt"
	"os"

	"github.com/codegangsta/cli"
)

func main() {
	app := cli.NewApp()
	app.Action = func(c *cli.Context) {
		fmt.Println(os.Getwd())
	}

	app.Run(os.Args)
}
➜  ~ go run tmp.go
/home/jesse <nil>
➜  ~ go version
go version go1.5.3 linux/amd64
```

Let me know if this helps!

**Comment by xuxiangyang** [comment]
thx, other package has change the dir.....sorry
