### ISSUE TITLE
Getting "DEPRECATED Action signature.  Must be `cli.ActionFunc`"

### ISSUE THREAD

**Issue by efairon** [codegangsta/cli#370]
Our applicaiton working for months.
Recompiled today with latest [cli ](https://github.com/codegangsta) update and we get this warning:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`
```

**Comment by jszwedko** [comment]
Hi @efairon!

This work was recently merged and released.

We are following [semantic versioning](http://semver.org/) and so this work involved bumping the minor version. We recommend pinning the version of this library to a particular minor version (using one of the many pinning tools) if you do not want to encounter deprecations (or vendoring).

You can see the [CHANGELOG](https://github.com/codegangsta/cli/blob/master/CHANGELOG.md) for the full list of changes.

Let me know what you think though! We've recently picked up steam again and are working through to make long overdue improvements to the library. We aim to do this in a backwards compatible fashion where possible, but this does involve deprecation of the usage of certain APIs to improve the overall API.

**Comment by meatballhat** [comment]
fwiw I've just merged some clarifications so that all deprecation warnings now include URLs to the relevant entry in the CHANGELOG :wave:

**Comment by efairon** [comment]
Ok clear. Thanks a lot.

**Comment by Shikkic** [comment]
I don't know if you were able to resolve this @efairon but I also got this a few days ago and I was able to fix it by now returning an `error` on the `Action: func().`

For example:
```
app.Commands = []cli.Command{
  {
    Name:    "search",
    Aliases: []string{"s"},
    Usage:   "Search go packages on gophr.pm",
    Action:  RunSearchCommand,
  }
}
```
```
func RunSearchCommand(c *cli.Context) error {
  ...
}
```

Doesn't give me the `DEPRECATED Action signature. Must be `cli.ActionFunc` message anymore.

**Comment by efairon** [comment]
@Shikkic Yes since we return error we got no problrm anymore. I should have written it in my previous comment.

Thanks.
