### ISSUE TITLE
Help does not display command aliases

### ISSUE THREAD

**Issue by jaroslaw-bochniak** [codegangsta/cli#405]
Hello,

First I would like to say that your project is awesome and it is the best CLI library I have used! Keep up the good work! Thank you for that.

I have a question related to latest version. Recently I have noticed that when displaying help it does no longer show aliases next to the command names. 

When command is defined in the following way, no aliases are shown in the help output
`{Name:     "nginx-start",
 Aliases:  []string{"ngstart", "nstart"},
 Category: cat(NginxCategory),}`

When deprecated ShortName is used instead Aliases, help does display alias properly.
`{
    Name:     "nginx-start",
    ShortName: "ngstart",
    Category: cat(NginxCategory),
    ...
}`

Is this change in behaviour intentional and we should define a custom help template or did it simply slipped during refactoring?

**Comment by meatballhat** [comment]
@jaroslaw-bochniak Thanks for the report!  I believe this was accidentally lost.

**Comment by meatballhat** [comment]
Bisecting leads me to a0801792cc2dc77e913bd8405d5ef0e2f5ba32e8, fwiw

**Comment by jaroslaw-bochniak** [comment]
Thanks guys! Works perfectly!
