### ISSUE TITLE
How do I extend the Context with custom info?

### ISSUE THREAD

**Issue by hafe** [codegangsta/cli#409]
Use case, as part of a common global setup I want to create/retrieve some info (like credentials) and later use it in command handlers.

Right now I use global variables because I haven't found a nice to achieve this.

Thanks,
Hans

**Comment by meatballhat** [comment]
@hafe are you able to use the `Metadata` member of `*cli.App` for this?

**Comment by hafe** [comment]
Sounds great but I need to update my cli version. It was rather old and didn't have this new stuff. Will try the latest version.
Thanks
