### ISSUE TITLE
Telnet interface

### ISSUE THREAD

**Issue by jefferai** [codegangsta/cli#41]
I'd love to be able to use cli.go to create a telnet interface for applications that would allow me to inspect and manipulate the program's running state. I haven't looked into how easy or difficult this would be, but consider it a wishlist item if you get the time for it  :-)

**Comment by jszwedko** [comment]
Indeed, I think this should be achievable by just calling `cli.Run` repeatedly with each line of input from the user similar to what @codegangsta is doing in codegangsta/hip, but please feel free to re-open if you think any changes are needed to this library to support this type of application interface.
