### ISSUE TITLE
Remove BoolTFlag

### ISSUE THREAD

**Issue by jszwedko** [codegangsta/cli#412]
I think it is simpler to just `Value` to `BoolFlag` for the defaulting logic.

**Comment by meatballhat** [comment]
Do you mean to *add* a `Value` member to the `BoolFlag` type?

**Comment by jszwedko** [comment]
Haha, yeah, verbs are cool. I guess.

:smile:

**Comment by jszwedko** [comment]
Fixed by #414 (to be released as v2)
