### ISSUE TITLE
allow actions to return its execution status.

### ISSUE THREAD

**Issue by AntonioMeireles** [codegangsta/cli#66]
Hi, 

Like what is already possible for 'Before' actions, i found useful and somewhat logical to  have 'Actions' return something on exit, so that app.Run() gets to catch  all errors, if any, underneath it. Please look at 52496bf2b67c04301dc20538a8a7736c11bc8bf6 in case you care. 

All the best

**Comment by jszwedko** [comment]
Will try to get #66 in soon.
