### ISSUE TITLE
Double dash for keyword flags vs single dash for character flags

### ISSUE THREAD

**Issue by smousa** [codegangsta/cli#87]
I noticed that in some applications, character flags are grouped by a single hyphen, while keyword flags must be prepended with a double-hyphen.

For example:
myapp -asdf

Would be the equivalent to:
myapp -a -s -d -f

However, 
myapp --asdf

Refers to the keyword flag 'asdf'

Is this something that may be considered for a later version?

**Comment by jszwedko** [comment]
We are at the mercy of the underlying `flag` parsing library on this one, but I agree that it could be something considered if we ever shifted away to our own parser.
