### ISSUE TITLE
Different Args in "Action" and "Before" functions

### ISSUE THREAD

**Issue by igm** [codegangsta/cli#92]
I recently came across a problem when accessing Args from Context. I expected to get the same args in "Action" and "Before" functions, but "Action" has it's name at index 0 and arguments start from index 1, in "Before" arguments start from index 0. 

An example to demonstrate: http://play.golang.org/p/CIrOdw3noq

Also looking at the examples https://github.com/codegangsta/cli#subcommands
I'd expect `c.Args().First()` to contain the first argument, not the command name itself. Is this desired behaviour, please?

**Comment by jszwedko** [comment]
Addressed by #170

**Comment by rawn** [comment]
Great, just found this bug as well and can confirm it. My research also found the lines above by ghigt. 

The Ctx context haven't yet parsed the flags for the subcommand, but context context has and that one is used by the Before action, which makes it look like it works for Before, but not Action of the subcommand.

Any ETA when a fix can be merged to master?

**Comment by jszwedko** [comment]
@rawn merged in today, let me know if your issue persists.

**Comment by rawn** [comment]
@jszwedko Works beautifully!
